/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package io.jcml.gephi.plugins.friendships;

/**
 *
 * @author jacomyal
 */
public class FriendshipsPanel extends javax.swing.JPanel {
    
    private Object bean;

    /**
     * Creates new customizer ReversePanel
     */
    public FriendshipsPanel() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    public float getP0Ratio() {
        try {
            return Float.parseFloat(p0RatioTextField.getText());
        } catch (Exception e) {}
        return -2;
    }

    public void setP0Ratio(float p0Ratio) {
        p0RatioTextField.setText(Float.toString(p0Ratio));
    }

    public float getP1Ratio() {
        try {
            return Float.parseFloat(p1RatioTextField.getText());
        } catch (Exception e) {}
        return 1;
    }

    public void setP1Ratio(float p1Ratio) {
        p1RatioTextField.setText(Float.toString(p1Ratio));
    }

    public float getP2Ratio() {
        try {
            return Float.parseFloat(p2RatioTextField.getText());
        } catch (Exception e) {}
        return 1;
    }

    public void setP2Ratio(float p2Ratio) {
        p2RatioTextField.setText(Float.toString(p2Ratio));
    }

    public float getP3Ratio() {
        try {
            return Float.parseFloat(p3RatioTextField.getText());
        } catch (Exception e) {}
        return 1;
    }

    public void setP3Ratio(float p3Ratio) {
        p3RatioTextField.setText(Float.toString(p3Ratio));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p0RatioLabel = new javax.swing.JLabel();
        p0RatioTextField = new javax.swing.JTextField();
        p1RatioLabel = new javax.swing.JLabel();
        p1RatioTextField = new javax.swing.JTextField();
        p2RatioLabel = new javax.swing.JLabel();
        p2RatioTextField = new javax.swing.JTextField();
        p3RatioLabel = new javax.swing.JLabel();
        p3RatioTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        p0RatioLabel.setText("Direct connections penalty");

        p0RatioTextField.setText("");
        p0RatioTextField.setMinimumSize(new java.awt.Dimension(59, 25));
        p0RatioTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        p1RatioLabel.setText("Common neighbors score (transitive edges)");

        p1RatioTextField.setText("");
        p1RatioTextField.setMinimumSize(new java.awt.Dimension(59, 25));
        p1RatioTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        p2RatioLabel.setText("Common neighbors score (common target)");

        p2RatioTextField.setText("");
        p2RatioTextField.setMinimumSize(new java.awt.Dimension(59, 25));
        p2RatioTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        p3RatioLabel.setText("Common neighbors score (common source)");

        p3RatioTextField.setText("");
        p3RatioTextField.setMinimumSize(new java.awt.Dimension(59, 25));
        p3RatioTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p3RatioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p3RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p2RatioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p2RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p1RatioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p1RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p0RatioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p0RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p0RatioLabel)
                    .addComponent(p0RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1RatioLabel)
                    .addComponent(p1RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2RatioLabel)
                    .addComponent(p2RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3RatioLabel)
                    .addComponent(p3RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel p0RatioLabel;
    protected javax.swing.JTextField p0RatioTextField;
    private javax.swing.JLabel p1RatioLabel;
    protected javax.swing.JTextField p1RatioTextField;
    private javax.swing.JLabel p2RatioLabel;
    protected javax.swing.JTextField p2RatioTextField;
    private javax.swing.JLabel p3RatioLabel;
    protected javax.swing.JTextField p3RatioTextField;
    // End of variables declaration//GEN-END:variables
}
