/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package io.jcml.gephi.plugins.abcd;

/**
 *
 * @author jacomyal
 */
public class ABCDPanel extends javax.swing.JPanel {
    
    private Object bean;

    /**
     * Creates new customizer ReversePanel
     */
    public ABCDPanel() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    public float getP0Ratio() {
        try {
            return Float.parseFloat(p0RatioTextField.getText());
        } catch (Exception e) {}
        return -2;
    }

    public void setP0Ratio(float p0Ratio) {
        p0RatioTextField.setText(Float.toString(p0Ratio));
    }

    public float getP1Ratio() {
        try {
            return Float.parseFloat(p1RatioTextField.getText());
        } catch (Exception e) {}
        return 1;
    }

    public void setP1Ratio(float p1Ratio) {
        p1RatioTextField.setText(Float.toString(p1Ratio));
    }

    public float getP2Ratio() {
        try {
            return Float.parseFloat(p2RatioTextField.getText());
        } catch (Exception e) {}
        return 1;
    }

    public void setP2Ratio(float p2Ratio) {
        p2RatioTextField.setText(Float.toString(p2Ratio));
    }

    public float getP3Ratio() {
        try {
            return Float.parseFloat(p3RatioTextField.getText());
        } catch (Exception e) {}
        return 1;
    }

    public void setP3Ratio(float p3Ratio) {
        p3RatioTextField.setText(Float.toString(p3Ratio));
    }

    public float getThreshold() {
        try {
            return Float.parseFloat(thresholdTextField.getText());
        } catch (Exception e) {}
        return 1;
    }

    public void setThreshold(float threshold) {
        thresholdTextField.setText(Float.toString(threshold));
    }

    public boolean getOverrideEdges() {
        try {
            return overrideEdgesCheckBox.isSelected();
        } catch (Exception e) {}
        return true;
    }

    public void setOverrideEdges(boolean overrideEdges) {
        overrideEdgesCheckBox.setSelected(overrideEdges);
    }

    public boolean getIgnoreEdgeWeights() {
        try {
            return ignoreEdgeWeightsCheckBox.isSelected();
        } catch (Exception e) {}
        return true;
    }

    public void setIgnoreEdgeWeights(boolean ignoreEdgeWeights) {
        ignoreEdgeWeightsCheckBox.setSelected(ignoreEdgeWeights);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        p0RatioLabel = new javax.swing.JLabel();
        p0RatioTextField = new javax.swing.JTextField();
        p1RatioLabel = new javax.swing.JLabel();
        p1RatioTextField = new javax.swing.JTextField();
        p2RatioLabel = new javax.swing.JLabel();
        p2RatioTextField = new javax.swing.JTextField();
        p3RatioLabel = new javax.swing.JLabel();
        p3RatioTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        thresholdTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        overrideEdgesCheckBox = new javax.swing.JCheckBox();
        ignoreEdgeWeightsCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.BorderLayout());

        p0RatioLabel.setText("Direct connections penalty");

        p0RatioTextField.setText("");
        p0RatioTextField.setMinimumSize(new java.awt.Dimension(59, 25));
        p0RatioTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        p1RatioLabel.setText("Common neighbors score (transitive edges)");

        p1RatioTextField.setText("");
        p1RatioTextField.setMinimumSize(new java.awt.Dimension(59, 25));
        p1RatioTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        p2RatioLabel.setText("Common neighbors score (common target)");

        p2RatioTextField.setText("");
        p2RatioTextField.setMinimumSize(new java.awt.Dimension(59, 25));
        p2RatioTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        p3RatioLabel.setText("Common neighbors score (common source)");

        p3RatioTextField.setText("");
        p3RatioTextField.setMinimumSize(new java.awt.Dimension(59, 25));
        p3RatioTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setText("If the graph is undirected, make sure to use the same value for the three \"Common neighbors score\" fields.");

        jLabel3.setText("Threshold");

        thresholdTextField.setText("jTextField1");

        jLabel4.setText("Override edges");

        overrideEdgesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overrideEdgesCheckBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Ignore edge weights");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Antagonism Based Community Detection");

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel7.setText("(modifies irreveribly the graph is set to true)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p3RatioLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(p3RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p2RatioLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(p2RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p1RatioLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(p1RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(p0RatioLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(p0RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(thresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ignoreEdgeWeightsCheckBox)
                                            .addComponent(overrideEdgesCheckBox)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel6)))
                .addGap(71, 160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p0RatioLabel)
                            .addComponent(p0RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(thresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p1RatioLabel)
                            .addComponent(p1RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(ignoreEdgeWeightsCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p2RatioLabel)
                        .addComponent(p2RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(overrideEdgesCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3RatioLabel)
                    .addComponent(p3RatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void overrideEdgesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overrideEdgesCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overrideEdgesCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ignoreEdgeWeightsCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox overrideEdgesCheckBox;
    private javax.swing.JLabel p0RatioLabel;
    protected javax.swing.JTextField p0RatioTextField;
    private javax.swing.JLabel p1RatioLabel;
    protected javax.swing.JTextField p1RatioTextField;
    private javax.swing.JLabel p2RatioLabel;
    protected javax.swing.JTextField p2RatioTextField;
    private javax.swing.JLabel p3RatioLabel;
    protected javax.swing.JTextField p3RatioTextField;
    private javax.swing.JTextField thresholdTextField;
    // End of variables declaration//GEN-END:variables
}
